config/routes.rb
Rails.application.routes.draw do

    resources :posts
    resources :pages # reemplaza todas las rutas que estan debajo, ya no hay que poner esos 7 metodos de manera manual, aunque eventualmente se va a necesitar hacer manual 
     
  #get  '/pages', to: 'pages#index'
  #post '/pages', to: 'pages#create'
  #get  '/pages/new', to: 'pages#new', as: 'new_page'
  #get  '/pages/:id', to: 'pages#show', as: 'page'
  #get  '/pages/:id/edit', to: 'pages#edit', as: 'edit_page'
  #patch  '/pages/:id', to: 'pages#update' # cuando los datos se van a actualizar en lugar de ser creador por primera vez se utiliza "patch"
  #delete '/pages/:id', to: 'pages#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]
    def index
        @pages = Page.all
    end 

    def show 
        #@page = Page.find(params[:id])
        #set_page
    end

    def new
        @page = Page.new
    end

    def create 
        #page_params = params.require(:page).permit(:title, :body, :slug)
        @page = Page.new(page_params)
        #set_page
        @page.save
        redirect_to @page
    end 


    

    def destroy 
        #@page = Page.find(params[:id])
        #set_page
        @page.destroy
        redirect_to pages_path
    end 

    def edit 
        #@page = Page.find(params[:id])
        #set_page
    end 
    
    def update 
        # Look up the existing model record based
        # on an ID from the request path.
        #@page = Page.find(params[:id])
        #set_page
        # Filter the form parameters to ensure no
        # malicious parameters were added.
        # Use the filtered parameters to update
        #page_params = params.require(:page).permit(:title, :body, :slug)

        # the existing model record.
        @page.update(page_params)
        # Redirect the browser to another location
        # so that it doesn't just sit there displaying
        # the submitted form.
        redirect_to @page
    end 

    private 

            def page_params #metodo para crear o editar objetos 
                    params.require(:page).permit(:title, :body, :slug)
            end 

            def set_page 
                    @page = Page.find(params[:id])

            end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    render template: "posts/index.html.erb", layout: "application"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>

    <div class= "field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>



    <div class= "field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>

    <div class= "field">
        <%= f.label :slug %>
        <%= f.text_field :slug %>
    </div>

    <div class= "field">
        <%= f.submit  %>
    </div>


<% end %>

app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<h1> Paginas Blog </h1>

<br>

<% @pages.each do |page| %>
    <p> <%= link_to page.title,  page_path(page) %> </p>
<% end %>

<br>
<%= link_to 'Nueva entrada del Blog', new_page_path %>

app/views/pages/new.html.erb
<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<p> <%= @page.body %> </p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Delete', @page, method: :delete %> 

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


    <div class="field">   <%# Se el rectangulo de body  %>
      <%= form.label :body %> <%# Se cambia al atributo body  %>
      <%= form.text_area :body %> <%# text_area agrega más area para agregar texto que text_field y se cambia al atributo body  %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th> 
      <th>Body</th>  <%# se muestra en pantalla el titulo del atributo "Body"  %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td> <%# Se muestra el contenido del atributo body del post  %>

        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>                                   <%# Se agrega el atributo body al cuerpo de la pagina que muestra las entragas del blog  %> 
  <strong>Body:</strong>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>